name: Build RPM

on:
  - push
  - pull_request

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        sparse-checkout: rpm.spec
        sparse-checkout-cone-mode: false

    - name: Install Dependencies
      run: dnf install -y rpmdevtools

    - name: Modify Spec
      if: github.ref_type != 'tag'
      run: |
        sed -i "s@/archive/refs/tags/%{version}.tar.gz@/archive/${GITHUB_SHA}.tar.gz@" rpm.spec
        sed -i "s@^%autosetup\$@%autosetup -n %{name}-${GITHUB_SHA}@" rpm.spec

    - name: Build RPM
      run: |
        spectool --get-files --directory=SOURCES --all rpm.spec
        dnf builddep -y rpm.spec
        rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -ba rpm.spec

    - name: Upload Artifact
      if: github.ref_type != 'tag'
      uses: actions/upload-artifact@v4
      with:
        name: rpm-package
        path: RPMS/*/*

    - name: Create Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        files: RPMS/*/*
